version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-bot
    restart: always
    volumes:
      - src:/app/src
      - node_modules:/app/node_modules
    env_file:
      - .env
    runtime: nvidia
    devices:
      - /dev/dri:/dev/dri
