version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-bot
    restart: always
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${PRIVATE_KEY}
      - APP_ID=${APP_ID}
    command: yarn start
