version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-bot
    restart: always
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: yarn start
